/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用户注册 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        username?: string;
                        /** Format: password */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description 注册成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登录（JWT） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 邮箱或用户名 */
                        account: string;
                        /** Format: password */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description 登录成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 刷新 token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refresh_token: string;
                    };
                };
            };
            responses: {
                /** @description 刷新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登出（吊销当前 token） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前用户信息与配额 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["Me"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** API Key 列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ListOk"];
            };
        };
        put?: never;
        /** 创建 API Key（明文仅此一次返回） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        scopes: ("read" | "backtest" | "factor" | "trade")[];
                    };
                };
            };
            responses: {
                /** @description 创建成功，返回明文 key（不再可查） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: {
                                id?: number;
                                /** @example wsq_AbC123_xxxxxxxxxxxxxxxxxxxx */
                                key?: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 吊销 API Key */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 数据集新鲜度与缺口 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["DatasetStatus"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 触发数据同步（异步） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        type?: "securities" | "daily_bars" | "indicators" | "calendar";
                        codes?: string[];
                        /** Format: date */
                        date_from?: string;
                    };
                };
            };
            responses: {
                200: components["responses"]["JobAccepted"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 导入导出文件（CSV/Parquet，异步） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file?: string;
                        /** @description 服务端可达路径（与 file 二选一） */
                        path?: string;
                    };
                };
            };
            responses: {
                200: components["responses"]["JobAccepted"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/securities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 证券列表 */
        get: {
            parameters: {
                query?: {
                    market?: string;
                    /** @description 关键字搜索 */
                    kw?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ListOk"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 交易日历 */
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ListOk"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/bars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 日K（DataFeed 代理，PIT） */
        get: {
            parameters: {
                query: {
                    code: string;
                    from?: string;
                    to?: string;
                    adjust?: "" | "qfq" | "hfq";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["Kline"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 策略列表 */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    size?: components["parameters"]["Size"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ListOk"];
            };
        };
        put?: never;
        /** 创建策略 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StrategyUpsert"];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["Strategy"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** 策略详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["Strategy"];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        /** 更新策略（生成新版本） */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["StrategyUpsert"];
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        post?: never;
        /** 删除策略 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** 版本列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ListOk"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies/{id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 校验策略（配置 schema / 代码沙箱） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
                422: components["responses"]["Unprocessable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategy-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 策略模板库 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ListOk"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backtests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 回测列表 */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    size?: components["parameters"]["Size"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ListOk"];
            };
        };
        put?: never;
        /** 创建回测（异步） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BacktestCreate"];
                };
            };
            responses: {
                200: components["responses"]["JobAccepted"];
                429: components["responses"]["QuotaExceeded"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backtests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** 回测详情与进度 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["Backtest"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backtests/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 取消回测 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backtests/{id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** 绩效指标 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["BacktestMetrics"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backtests/{id}/equity": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** 净值序列 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["EquityPoint"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backtests/{id}/trades": {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** 交易明细 */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    size?: components["parameters"]["Size"];
                };
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ListOk"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backtests/{id}/positions": {
        parameters: {
            query?: {
                date?: string;
            };
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** 每日持仓 */
        get: {
            parameters: {
                query?: {
                    date?: string;
                };
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ListOk"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/optimizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 参数寻优（批量回测，异步） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BacktestCreate"] & {
                        param_grid?: {
                            [key: string]: unknown[];
                        };
                        /**
                         * @default grid
                         * @enum {string}
                         */
                        method?: "grid" | "random";
                    };
                };
            };
            responses: {
                200: components["responses"]["JobAccepted"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backtests/{id}/report": {
        parameters: {
            query?: {
                format?: "html" | "pdf";
            };
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** 绩效报告 */
        get: {
            parameters: {
                query?: {
                    format?: "html" | "pdf";
                };
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 报告内容（html）或下载（pdf） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 多回测对比 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        backtest_ids?: number[];
                    };
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backtests/{id}/share": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 生成只读分享链接 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description 秒 */
                        expires_in?: number;
                    };
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: {
                                url?: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/factors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 因子列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ListOk"];
            };
        };
        put?: never;
        /** 创建因子 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FactorUpsert"];
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/factors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** 因子详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        put?: never;
        post?: never;
        /** 删除因子 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/factors/{id}/compute": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 计算因子值（异步） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        universe?: components["schemas"]["Universe"];
                        /** Format: date */
                        date_from?: string;
                        /** Format: date */
                        date_to?: string;
                    };
                };
            };
            responses: {
                200: components["responses"]["JobAccepted"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/factors/{id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 因子检验 IC/分层（异步） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @default 5 */
                        forward_period?: number;
                        /** @default 5 */
                        n_quantiles?: number;
                        neutralize?: ("industry" | "market_cap")[];
                    };
                };
            };
            responses: {
                200: components["responses"]["JobAccepted"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/factors/{id}/analyses/{aid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
                aid: number;
            };
            cookie?: never;
        };
        /** 因子分析结果 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                    aid: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["FactorAnalysis"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/factors/combine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 多因子合成 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name?: string;
                        members?: {
                            factor_id?: number;
                            weight?: number;
                        }[];
                        /**
                         * @default equal
                         * @enum {string}
                         */
                        scheme?: "equal" | "ic_weight" | "regression";
                        neutralize?: string[];
                    };
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 组合列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ListOk"];
            };
        };
        put?: never;
        /** 创建组合 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PortfolioUpsert"];
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** 组合详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["Portfolio"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** 删除组合 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{id}/positions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** 当前持仓 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ListOk"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{id}/rebalance": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 触发再平衡（生成订单，过风控） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{id}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** 订单列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ListOk"];
            };
        };
        put?: never;
        /** 手动下单（过风控） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OrderCreate"];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["Order"];
                        };
                    };
                };
                403: components["responses"]["Forbidden"];
                422: components["responses"]["RiskRejected"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 撤单 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{id}/trades": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** 成交列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ListOk"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{id}/signals": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** 调仓信号建议（用于人工执行/跟单） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ListOk"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risk/rule-sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 风控规则集列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ListOk"];
            };
        };
        put?: never;
        /** 创建风控规则集 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RiskRuleSet"];
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risk/rule-sets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get?: never;
        /** 更新风控规则集 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RiskRuleSet"];
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        post?: never;
        /** 删除风控规则集 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risk/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 风控事件 */
        get: {
            parameters: {
                query?: {
                    portfolio_id?: number;
                    page?: components["parameters"]["Page"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ListOk"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 告警渠道列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ListOk"];
            };
        };
        put?: never;
        /** 创建告警渠道 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        type: "email" | "webhook" | "dingtalk" | "feishu" | "serverchan";
                        config: Record<string, never>;
                    };
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/channels/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除告警渠道 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 告警记录 */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    size?: components["parameters"]["Size"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ListOk"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 任务列表 */
        get: {
            parameters: {
                query?: {
                    type?: string;
                    page?: components["parameters"]["Page"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ListOk"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** 任务状态与进度 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["Job"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 用户列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ListOk"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get?: never;
        /** 更新用户（角色/套餐/配额/启停/实盘授权） */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        role?: "user" | "admin";
                        plan?: string;
                        /** @enum {string} */
                        status?: "active" | "disabled";
                        live_enabled?: boolean;
                    };
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/data-source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** data 服务凭证列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ListOk"];
            };
        };
        put?: never;
        /** 配置 data 服务凭证（secretKey 仅写入不回显） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        base_url: string;
                        secret_id: string;
                        secret_key: string;
                        qps_limit?: number;
                        daily_quota?: number;
                    };
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 套餐列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ListOk"];
            };
        };
        put?: never;
        /** 创建/更新套餐 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        code?: string;
                        name?: string;
                        limits?: Record<string, never>;
                    };
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 审计日志检索 */
        get: {
            parameters: {
                query?: {
                    actor_id?: number;
                    action?: string;
                    page?: components["parameters"]["Page"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ListOk"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/system/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 系统任务监控 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ListOk"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康检查 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prometheus 指标 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 指标文本 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description 高精度数值字符串，如 "10.5000"
         * @example 10.5000
         */
        Decimal: string;
        ApiResponse: {
            /** @example 0 */
            code?: number;
            /** @example ok */
            message?: string;
            data?: unknown;
        };
        PageData: {
            list?: unknown[];
            total?: number;
            page?: number;
            size?: number;
        };
        TokenResponse: components["schemas"]["ApiResponse"] & {
            data?: {
                access_token?: string;
                refresh_token?: string;
                /** @example bearer */
                token_type?: string;
                expires_in?: number;
            };
        };
        Me: {
            id?: number;
            email?: string;
            username?: string;
            /** @enum {string} */
            role?: "user" | "admin";
            plan?: string;
            live_enabled?: boolean;
            /** @description 配额用量 */
            quota?: Record<string, never>;
        };
        DatasetStatus: {
            /** Format: date */
            latest_trade_date?: string;
            /** Format: date */
            bars_updated_to?: string;
            securities_count?: number;
            gaps?: string[];
            stale?: boolean;
        };
        Kline: {
            /** Format: date */
            date?: string;
            open?: components["schemas"]["Decimal"];
            high?: components["schemas"]["Decimal"];
            low?: components["schemas"]["Decimal"];
            close?: components["schemas"]["Decimal"];
            volume?: components["schemas"]["Decimal"];
            amount?: components["schemas"]["Decimal"];
        };
        /** @description 股票池定义 */
        Universe: {
            /**
             * @default all
             * @enum {string}
             */
            type: "all" | "index" | "list" | "factor";
            /** @description 指数代码（type=index） */
            code?: string;
            /** @description 自定义列表（type=list） */
            codes?: string[];
            /** @description 因子筛选（type=factor） */
            filter?: Record<string, never>;
        };
        StrategyUpsert: {
            name: string;
            /**
             * @default config
             * @enum {string}
             */
            type: "config" | "code";
            description?: string;
            /** @description 配置式策略积木 */
            config?: Record<string, never>;
            /** @description 代码式 backtrader Strategy 源码 */
            code?: string;
            params_schema?: Record<string, never>;
            default_params?: Record<string, never>;
            universe?: components["schemas"]["Universe"];
        };
        Strategy: components["schemas"]["StrategyUpsert"] & {
            id?: number;
            latest_version?: number;
            /** Format: date-time */
            created_at?: string;
        };
        BacktestCreate: {
            name?: string;
            strategy_version_id: number;
            params?: Record<string, never>;
            universe?: components["schemas"]["Universe"];
            /** Format: date */
            date_from: string;
            /** Format: date */
            date_to: string;
            /** @example 1000000 */
            init_capital: number;
            /** @default 000300 */
            benchmark: string;
            /**
             * @default qfq
             * @enum {string}
             */
            adjust: "" | "qfq" | "hfq";
            cost_config?: {
                /** @default 0.0003 */
                commission_rate: number;
                /** @default 5 */
                commission_min: number;
                /** @default 0.0005 */
                stamp_tax_rate: number;
                /**
                 * @default pct
                 * @enum {string}
                 */
                slippage_type: "none" | "pct" | "tick" | "volume";
                /** @default 0.0005 */
                slippage_value: number;
            };
        };
        Backtest: {
            id?: number;
            name?: string;
            /** @enum {string} */
            status?: "queued" | "running" | "succeeded" | "failed" | "canceled";
            progress?: components["schemas"]["Decimal"];
            job_id?: string;
            /** Format: date */
            date_from?: string;
            /** Format: date */
            date_to?: string;
            error?: string;
            /** Format: date-time */
            created_at?: string;
        };
        BacktestMetrics: {
            total_return?: components["schemas"]["Decimal"];
            annual_return?: components["schemas"]["Decimal"];
            volatility?: components["schemas"]["Decimal"];
            sharpe?: components["schemas"]["Decimal"];
            sortino?: components["schemas"]["Decimal"];
            calmar?: components["schemas"]["Decimal"];
            max_drawdown?: components["schemas"]["Decimal"];
            /** Format: date */
            mdd_from?: string;
            /** Format: date */
            mdd_to?: string;
            win_rate?: components["schemas"]["Decimal"];
            profit_factor?: components["schemas"]["Decimal"];
            turnover?: components["schemas"]["Decimal"];
            alpha?: components["schemas"]["Decimal"];
            beta?: components["schemas"]["Decimal"];
            info_ratio?: components["schemas"]["Decimal"];
        };
        EquityPoint: {
            /** Format: date */
            trade_date?: string;
            nav?: components["schemas"]["Decimal"];
            benchmark_nav?: components["schemas"]["Decimal"];
            drawdown?: components["schemas"]["Decimal"];
        };
        FactorUpsert: {
            name: string;
            category?: string;
            /**
             * @default expr
             * @enum {string}
             */
            type: "expr" | "code" | "builtin";
            /** @example rank(-pct_change(close, 20)) */
            expr?: string;
            code?: string;
            params?: Record<string, never>;
            /**
             * @default 1
             * @enum {integer}
             */
            direction: 1 | -1;
        };
        FactorAnalysis: {
            id?: number;
            status?: string;
            forward_period?: number;
            n_quantiles?: number;
            ic_mean?: components["schemas"]["Decimal"];
            ic_ir?: components["schemas"]["Decimal"];
            ic_win_rate?: components["schemas"]["Decimal"];
            ic_series?: Record<string, never>[];
            quantile_returns?: Record<string, never>;
            turnover?: Record<string, never>;
        };
        PortfolioUpsert: {
            name: string;
            /**
             * @default paper
             * @enum {string}
             */
            mode: "paper" | "live";
            strategy_version_id?: number;
            init_capital: number;
            /** @default 000300 */
            benchmark: string;
            /**
             * @default week
             * @enum {string}
             */
            rebalance: "day" | "week" | "month";
            weight_scheme?: Record<string, never>;
            risk_rule_set_id?: number;
        };
        Portfolio: components["schemas"]["PortfolioUpsert"] & {
            id?: number;
            cash?: components["schemas"]["Decimal"];
            market_value?: components["schemas"]["Decimal"];
            nav?: components["schemas"]["Decimal"];
            status?: string;
        };
        OrderCreate: {
            code: string;
            /** @enum {string} */
            side: "buy" | "sell";
            /**
             * @default limit
             * @enum {string}
             */
            order_type: "limit" | "market";
            price?: number;
            /** @description 100 股整数倍 */
            qty: number;
        };
        Order: {
            id?: number;
            code?: string;
            side?: string;
            price?: components["schemas"]["Decimal"];
            qty?: number;
            filled_qty?: number;
            /** @enum {string} */
            status?: "created" | "risk_rejected" | "submitted" | "partial" | "filled" | "canceled" | "rejected";
            /** @enum {string} */
            gateway?: "paper" | "xtp" | "tora" | "ost" | "emt";
            reason?: string;
            /** Format: date-time */
            created_at?: string;
        };
        RiskRuleSet: {
            name: string;
            /**
             * @default portfolio
             * @enum {string}
             */
            scope: "portfolio" | "account";
            rules: {
                /** @enum {string} */
                type?: "max_position_pct" | "max_industry_pct" | "max_count" | "max_order_amount" | "max_daily_amount" | "blacklist" | "whitelist" | "no_st" | "no_new" | "tradable" | "stop_loss" | "take_profit" | "trailing_stop" | "max_drawdown";
                params?: Record<string, never>;
                /**
                 * @default reject
                 * @enum {string}
                 */
                action: "reject" | "alert" | "liquidate";
                /** @default true */
                enabled: boolean;
            }[];
        };
        Job: {
            id?: string;
            /** @enum {string} */
            type?: "backtest" | "factor" | "data_sync" | "rebalance" | "trade" | "optimization";
            ref_id?: number;
            /** @enum {string} */
            status?: "queued" | "running" | "succeeded" | "failed" | "canceled";
            progress?: components["schemas"]["Decimal"];
            result?: Record<string, never>;
            error?: string;
            /** Format: date-time */
            created_at?: string;
        };
    };
    responses: {
        /** @description 操作成功 */
        Ok: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiResponse"];
            };
        };
        /** @description 分页列表 */
        ListOk: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiResponse"] & {
                    data?: components["schemas"]["PageData"];
                };
            };
        };
        /** @description 任务已入队（code=60001） */
        JobAccepted: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiResponse"] & {
                    /** @example 60001 */
                    code?: number;
                    data?: {
                        /** @description 资源 id */
                        id?: number;
                        job_id?: string;
                    };
                };
            };
        };
        /** @description 参数错误 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": 10001,
                 *       "message": "参数错误",
                 *       "data": null
                 *     }
                 */
                "application/json": components["schemas"]["ApiResponse"];
            };
        };
        /** @description 未认证 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": 40101,
                 *       "message": "未认证",
                 *       "data": null
                 *     }
                 */
                "application/json": components["schemas"]["ApiResponse"];
            };
        };
        /** @description 权限不足/越权 */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": 40301,
                 *       "message": "越权访问",
                 *       "data": null
                 *     }
                 */
                "application/json": components["schemas"]["ApiResponse"];
            };
        };
        /** @description 资源不存在 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": 10002,
                 *       "message": "资源不存在",
                 *       "data": null
                 *     }
                 */
                "application/json": components["schemas"]["ApiResponse"];
            };
        };
        /** @description 冲突 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": 10003,
                 *       "message": "资源冲突",
                 *       "data": null
                 *     }
                 */
                "application/json": components["schemas"]["ApiResponse"];
            };
        };
        /** @description 校验失败（沙箱/配置） */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": 61001,
                 *       "message": "策略校验失败",
                 *       "data": null
                 *     }
                 */
                "application/json": components["schemas"]["ApiResponse"];
            };
        };
        /** @description 风控拦截 */
        RiskRejected: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": 62001,
                 *       "message": "风控拦截：单票仓位超限",
                 *       "data": null
                 *     }
                 */
                "application/json": components["schemas"]["ApiResponse"];
            };
        };
        /** @description 配额超限 */
        QuotaExceeded: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": 42902,
                 *       "message": "超出配额",
                 *       "data": null
                 *     }
                 */
                "application/json": components["schemas"]["ApiResponse"];
            };
        };
    };
    parameters: {
        IdPath: number;
        Page: number;
        Size: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
